### ISSUE TITLE
Jabba for Raspberry Pi with opensuse 64 bits

### ISSUE THREAD

**Issue by craig42** [shyiko/jabba#100]
The script installs an Intel 64 bits version on opensuse aarch64.

**Comment by shyiko** [comment]
@craig42 Hi. Can you please check the result of `uname -m` and `getconf LONG_BIT` (per [install.sh](https://github.com/shyiko/jabba/blob/master/install.sh#L42))?

**Comment by craig42** [comment]
Ok , here are the results

`linux:~ # getconf LONG_BIT`
`64`
`linux:~ # uname -m`
`aarch64`

**Comment by shyiko** [comment]
@craig42 Thank you. Fixed in https://github.com/shyiko/jabba/commit/20cd98ae3caf2b30d0933c0958ecab71c3bccafb.
