### ISSUE TITLE
Use API for AdoptOpenJDK binaries

### ISSUE THREAD

**Issue by gdams** [shyiko/jabba#102]
I have noticed that you are hard coding the paths to our AdoptOpenJDK binaries.

I would strongly suggest that you explore using our API at https://api.adoptopenjdk.net as we already automate a lot of the steps for you :)

**Comment by shyiko** [comment]
Thanks for the ticket, George! I'm actually using that API endpoint in [jabba-autodiscovery](https://github.com/shyiko/jabba-autodiscovery) (https://github.com/shyiko/jabba-autodiscovery/blob/master/index.js#L75) which makes sure [index.json](https://github.com/shyiko/jabba/blob/master/index.json) is refreshed every 24h. Everything is automated ;)
