### ISSUE TITLE
Error when installing Zulu (and others) of Java versions in Windows

### ISSUE THREAD

**Issue by ivanqueiroz** [shyiko/jabba#116]
When I try to install Zulu, it´s show a erro:

PS C:\WINDOWS\system32> jabba install zulu@1.8.152
Downloading zulu@1.8.152 (http://cdn.azul.com/zulu/bin/zulu8.25.0.1-jdk8.0.152-win_x64.zip)
79704848/-1
Extracting C:\Users\ivanq\AppData\Local\Temp\jabba-d-993552483 to D:\Desenvolvimento\Ferramentas\.jabba\jdk\zulu@1.8.152

D:\Desenvolvimento\Ferramentas\.jabba\jdk\zulu@1.8.152\bin\java.exe wasn't found. If you believe this is an error - plea
se create a ticket at https://github.com/shyiko/jabba/issue (specify OS and command that was used)

I think the problem is the downloaded zip format file isn´t the expected by the jabba exe (because of folder inside zip).

**Comment by shyiko** [comment]
@ivanqueiroz thank you for the ticket. Fixed in [0.9.2](https://github.com/shyiko/jabba/blob/master/CHANGELOG.md#092---2017-11-18). I've also created [a ticket to make sure this does not happen again](https://github.com/shyiko/jabba/issues/118).

**Comment by ivanqueiroz** [comment]
@shyiko thank you for the fast resolution! Jabba is a great tool!
