### ISSUE TITLE
Installation instructions are dangerous for Linux/Mac

### ISSUE THREAD

**Issue by gavinws** [shyiko/jabba#12]
Like many other projects, the installation instructions for *nix users are dangerous. I suggest providing safer instructions or some other method that doesn't maintain the habit of running arbitrary code from the paste buffer. It could be as simple as first downloading and verifying the file before running it - and not pipe it to bash at all.

References:

https://blog.chef.io/2015/07/16/5-ways-to-deal-with-the-install-sh-curl-pipe-bash-problem/

https://www.idontplaydarts.com/2016/04/detecting-curl-pipe-bash-server-side/

https://github.com/ellotheth/pipethis

**Comment by shyiko** [comment]
Hey @gavinws. 

Thanks for the ticket but I'm not sure what else can be done given that:
1. executing any third-party code is inherently dangerous no matter who signed it
2. installer is `curl`ed from **github.com over HTTPS** and not from some shady mydomain.org
3. you can always [inspect the code](https://github.com/shyiko/jabba/blob/master/install.sh) if feel like it
4. while looking through the code before executing is generally a good idea it's often impractical (take nvm's >3k lines of bash for example) so very few people care/actually do it

I'm open to the suggestions though.
