### ISSUE TITLE
current index for ls-remote corrupt?

### ISSUE THREAD

**Issue by adminradio** [shyiko/jabba#126]
I'm new to jabba but it seems like that the index (at least for windws) is corrupt. ls-remotes lists actual sdk as single numbers (without sdk@ prefix), i.e: 1.9.0

**Comment by shyiko** [comment]
Hi Timm. That's OK. Entries without sdk@ point to `oracle`. A year ago ([before Oracle started asking for an account to download JDK](https://github.com/shyiko/jabba/issues/81)) that looked like a reasonable default but not anymore, obviously. This is going to change in jabba 1.0.0 (where oracle@ will have to be specified explicitly).

**Comment by adminradio** [comment]
Ah, understand. Thank you.
