### ISSUE TITLE
No such file or directory?zsh!!

### ISSUE THREAD

**Issue by uncle-link** [shyiko/jabba#139]
when I try the cmd in zsh It shows error as below
![image](https://user-images.githubusercontent.com/15264018/35326601-277092ae-0132-11e8-8027-da6475cc4224.png)
and then I try to change the command's bash to zsh, unfortunately error is continuous:(
![image](https://user-images.githubusercontent.com/15264018/35326684-59ea2a4c-0132-11e8-804c-9f5f6a7ce3b9.png)
and then I try to wget the install.sh and try execute it but error still exists
![image](https://user-images.githubusercontent.com/15264018/35326755-95cb80d8-0132-11e8-8a45-3a1466ae687f.png)
pls help me!

**Comment by shyiko** [comment]
Hi @uncle-link. It looks like https://github.com/shyiko/jabba/raw/master/install.sh isn't reachable (are you bind a proxy? if so - see https://github.com/shyiko/jabba#macos--linux footnote). Try executing 
`curl -sSL https://github.com/shyiko/jabba/raw/master/install.sh` and then check the content (it should match https://github.com/shyiko/jabba/blob/master/install.sh) (`curl -v -sSL ...` to get more info).

**Comment by uncle-link** [comment]
Well done! It's proxy's fault! when I change a proxy or unbind it, that was installed successfully!

**Comment by 547377507** [comment]
six six six
