### ISSUE TITLE
PowerShell Alias 

### ISSUE THREAD

**Issue by FerreiraRaphael** [shyiko/jabba#144]
So I have the following PowerShell Alias

````
function SetJava-7 {
    Invoke-Expression "& `"C:\Users\{user_name}\.jabba\bin\jabba.exe`" use zulu@1.7"
}

function SetJava-8 {
    Invoke-Expression "& `"C:\Users\{user_name}\.jabba\bin\jabba.exe`" use zulu@1.8"
}
````

Set them like this :

````
New-Alias sj7 SetJava-7

New-Alias sj8 SetJava-8
````

I run them and it's ok, it works, but the java version isn't changed, when I use the jabba command directly like bellow, it works, :

```
jabba use zulu@1.7
```

Can you guys give some help ?

**Comment by shyiko** [comment]
Hi Raphael.
You need to use [jabba PowerShell function](https://github.com/shyiko/jabba/blob/master/install.ps1#L48) instead of the binary (in short, when you `jabba install`, `jabba use`, etc. jabba binary outputs a set of `export VAR=VAL` pairs which jabba PowerShell function evaluates in the context of the shell).

**Comment by FerreiraRaphael** [comment]
Hi @shyiko, 
thanks for the quick reply, can you give a simple example of how to use this function ? Sorry I'm a newbie at powershell

**Comment by shyiko** [comment]
Provided you followed https://github.com/shyiko/jabba#windows-10 jabba should be available simply as `jabba`, in other words things like `jabba use zulu@1.7` should work. If it doesn't - then something is wrong.

**Comment by FerreiraRaphael** [comment]
@shyiko,
Going to test it later today, thanks !

**Comment by FerreiraRaphael** [comment]
@shyiko,
try it, and it didn't work, but I'm closing this issue, because i'm back to the good old linux.
