### ISSUE TITLE
please, add the openJDK last JDK10 build again

### ISSUE THREAD

**Issue by svenruppert** [shyiko/jabba#167]

**Comment by shyiko** [comment]
Hi Sven. 
Do you mean JDK build before https://github.com/shyiko/jabba/commit/2019f4c9f80fdf2b992fa7d1d8061ebaee1ccdcd? (if yes then it appears to be no longer available - `jabba install 1.10.0-46=tgz+http://download.java.net/java/jdk10/archive/46/BCL/jdk-10+46_linux-x64_bin.tar.gz` fails). 
In general: I do not remove builds unless links stop working and I can't find another way to access them (Oracle and IBM are known to do that, unfortunately).

**Comment by svenruppert** [comment]
shit, but ok. not checked if the link is still working. Sorry for this.

**Comment by svenruppert** [comment]
found it : https://download.java.net/java/GA/jdk10/10/binaries/openjdk-10_linux-x64_bin.tar.gz

**Comment by shyiko** [comment]
Thank you. Added in https://github.com/shyiko/jabba/commit/570ef01c7bfded4f6339f9d6cc0ac828b2aa5c62.

**Comment by shyiko** [comment]
EAP added in https://github.com/shyiko/jabba/commit/88ff2155cab05bcea01b4b4c5cf8dca9f0adab99.
