### ISSUE TITLE
oracle images -- linux -- no download - 8 / 9 / 10 

### ISSUE THREAD

**Issue by svenruppert** [shyiko/jabba#168]
Looks like the agreement is not accepted...

Downloading 1.10.0 (http://download.oracle.com/otn-pub/java/jdk/10+46/76eac37278c24557a3c4199677f19b62/jdk-10_linux-x64_bin.tar.gz) 
7073/7073
Extracting /tmp/jabba-d-022549645 to /jdk 
gzip: invalid header

**Comment by shyiko** [comment]
My only guess is that download.oracle.com was temporarily unavailable (e.g. 503). Looks like everything is back to normal: 
```sh
$ jabba install 1.10
Downloading 1.10.0 (http://download.oracle.com/otn-pub/java/jdk/10+46/76eac37278c24557a3c4199677f19b62/jdk-10_linux-x64_bin.tar.gz) 
^C82224/354809195
$ jabba install 1.9
Downloading 1.9.0 (http://download.oracle.com/otn-pub/java/jdk/9.0.4+11/c2514751926b4512b076cc82f959763f/jdk-9.0.4_linux-x64_bin.tar.gz) 
^C25/354635831
$ jabba install 1.8
Downloading 1.8.162 (http://download.oracle.com/otn-pub/java/jdk/8u162-b12/0da788060d494f5095bf8624735fa2f1/jdk-8u162-linux-x64.tar.gz) 
^C23/189815615
```
