### ISSUE TITLE
please add the management for GraalVM OS and Enterprise

### ISSUE THREAD

**Issue by svenruppert** [shyiko/jabba#180]
https://www.graalvm.org/downloads/

**Comment by shyiko** [comment]
Hi Sven. Added in https://github.com/shyiko/jabba/pull/183 (CE only, EE requires authorization).

```sh
$ jabba install graalvm@1.0.0-1
$ java -version
openjdk version "1.8.0_161"
OpenJDK Runtime Environment (build 1.8.0_161-12)
GraalVM 1.0.0-rc1 (build 25.71-b01-internal-jvmci-0.42, mixed mode)
```

**Comment by shyiko** [comment]
For the record, you can manage EE edition with

**Comment by shyiko** [comment]
Just so that it would be clear: EE edition can be managed by jabba. It's the `install graalvm-ee@<version>` part that is missing. In other words, the following should work:
 
```sh
jabba install graalvm-ee@1.0.0-1=tgz+file://path/to.tar.gz

# when you need EE execute
jabba use graalvm-ee@1.0.0-1
java -version
```

**Comment by svenruppert** [comment]
cool and thx
