### ISSUE TITLE
Windows installation fails

### ISSUE THREAD

**Issue by gregorko** [shyiko/jabba#185]
The windows installation instruction do not work for me.

I get the following error

```
Could not create SSL/TLS secure channel.
In Line:2
+         wget https://github.com/shyiko/jabba/raw/master/install.ps1 - ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

```
I changed the path to: https://raw.githubusercontent.com/shyiko/jabba/master/install.ps1
Which then gives me a similar error:

```
Could not create SSL/TLS secure channel.
In Line:29
+     wget https://github.com/shyiko/jabba/releases/download/$jabbaVers ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

**Comment by adarro** [comment]
I just ran into this same issue trying to upgrade some of my jabba installs.  
A quick SO search seems to indicate a protocol issue. (https://stackoverflow.com/questions/41618766/powershell-invoke-webrequest-fails-with-ssl-tls-secure-channel)
in powershell, viewing my SSL / TLS settings via
`[Net.ServicePointManager]::SecurityProtocol`
showed Ssl3, Tls
Changing it to Tls2  via
`[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12`

and then re-running the web request
```
Invoke-Expression (
        wget https://github.com/shyiko/jabba/raw/master/install.ps1 -UseBasicParsing
    ).Content

```
Seemed to do the trick.

HTH

**Comment by shyiko** [comment]
Thank you for the info, Andre. README updated.
