### ISSUE TITLE
Support for Shenandoah builds

### ISSUE THREAD

**Issue by 2m** [shyiko/jabba#191]
Would jabba be a good place to add support for JVM builds with [Shenandoah](https://wiki.openjdk.java.net/display/shenandoah/Main)?

Binary builds [are provided](https://wiki.openjdk.java.net/display/shenandoah/Main#Main-BinaryDevelopmentBuilds) by the build farm. The build numbers change daily, and only seven of the last ones are available to download. I would imagine the auto-discovery for `index.json` will have to be changed to support this.

I am willing to help out if you think this is a good idea.

P.S. I am a maintainer of [JDK8 Shenandoah build for ArchLinux](https://aur.archlinux.org/packages/java-8-openjdk-shenandoah/). Always changing build numbers make it tedious keeping the PKGBUILD definition up to date. I think having support for jabba would be a better approach.

**Comment by shyiko** [comment]
Hi Martynas. 

Sure, openjdk-shenandoah@1.{8,9,10}.* added (synced every 24h). 

You'll need [jabba@0.10.0+](https://github.com/shyiko/jabba/blob/master/CHANGELOG.md) for installation to work (tar.xz is not supported by jabba pre 0.10.0).

```sh
$ jabba install openjdk-shenandoah@1.10.0-235
$ java --version

openjdk 10.0.1-internal 2018-04-17
OpenJDK Runtime Environment (build 10.0.1-internal+0-nightly-sobornost-builds.shipilev.net-shenandoah-jdk10-b235)
OpenJDK 64-Bit Server VM (build 10.0.1-internal+0-nightly-sobornost-builds.shipilev.net-shenandoah-jdk10-b235, mixed mode)
```

:tada:

**Comment by 2m** [comment]
Oh wow. Thanks a lot for such a quick fix! :D
