### ISSUE TITLE
Link: .jabba/jdk folder not created automatically

### ISSUE THREAD

**Issue by davidecavestro** [shyiko/jabba#24]
Trying to link an old existing jdk on Linux
```jabba link system@1.6.29 /home/davide/opt/jdk1.6.0_29```
jabba fails complaining
```symlink /home/davide/opt/jdk1.6.0_29 /home/davide/.jabba/jdk/system@1.6.29: no such file or directory```
The missing folder is _/home/davide/.jabba/jdk_.
The issue disappears after running
```mkdir -p /home/davide/.jabba/jdk``` 

I guess it is an uncommon corner case, since on this host/user combo Jabba has never been used previously. It follows that the folder has not been created by means of other commands.

**Comment by shyiko** [comment]
@davidecavestro Thank you for ticket. I appreciate that :bowing_man:

**Comment by shyiko** [comment]
Fixed in 0.5.1.
