### ISSUE TITLE
 jabba ls-remote for other platforms

### ISSUE THREAD

**Issue by svenruppert** [shyiko/jabba#240]
Hi,
I often have to check the JDK version for an other platform.
I am developing under OSX, but servers are running on Linux.
It would be cool to have to possibility to use the CLI for 
checking JDK-version based on different platform. 

Idea: jabba ls-remote --linux

Cheers Sven

**Comment by BugDiver** [comment]
@svenruppert  This feature request has been addressed through https://github.com/shyiko/jabba/pull/292.

**Comment by shyiko** [comment]
Included in [0.11.0](https://github.com/shyiko/jabba/blob/master/CHANGELOG.md#0110---2018-10-11).
