### ISSUE TITLE
Move index.json to different repository

### ISSUE THREAD

**Issue by 2m** [shyiko/jabba#265]
Would it be possible to move [index.json](https://github.com/shyiko/jabba/blob/master/index.json) to a different repository and have jabba to query it from there?

Currently the history of this repo has a bit of noise due to autodiscovery process committing quite frequently.

**Comment by shyiko** [comment]
Yep, upcoming jabba v1 has index in a separate repo - https://github.com/jabba-registry/jabba-registry.github.io.

**Comment by 2m** [comment]
Ahh, very nice!
