### ISSUE TITLE
add IBM JDK

### ISSUE THREAD

**Issue by svenruppert** [shyiko/jabba#27]
would it possible to add IBM ? 

http://www.ibm.com/developerworks/java/jdk/index.html

**Comment by shyiko** [comment]
Sure. It would simply be a matter of adding URLs to [index.json](https://github.com/shyiko/jabba/blob/master/index.json) as `jdk@ibm` (same as `jdk@zulu`) if only IBM didn't use InstallAnywhere ([installation instructions](http://www.ibm.com/support/knowledgecenter/SSYKE2_8.0.0/com.ibm.java.aix.80.doc/user/ia_install_unattended.html)). I'll make necessary changes over the weekend.

**Comment by shyiko** [comment]
@svenruppert done (please upgrade jabba to 0.6.0). I've also enabled https://github.com/shyiko/jabba-autodiscovery which means every time there is an update (Oracle/Zulu/IBM) - jabba will :sparkles: automatically :sparkles: get a PR with all the new versions. Run by cron (daily) on Travis CI.
