### ISSUE TITLE
Installation fails in docker container

### ISSUE THREAD

**Issue by BugDiver** [shyiko/jabba#295]
The install scripts fails to install `jabba` in a docker container.
It needs `wget` to  be installed. The containre has `curl` installed already.
I hope it is handled somewhere for darwin.
Can we just fallback to curl if `wget` not found?

## Steps to replicate

* pull `centos` docker image by running `docker pull centos`
* `docker run -it centos /bin/bash`
* `curl --version` (make sure curl is installed)
* `wget --version` (make sure wget is _**not**_ installed)
*  Run `curl -sL https://github.com/shyiko/jabba/raw/master/install.sh | bash && . ~/.jabba/jabba.sh`
* Get the error
```
bash: line 28: wget: command not found
'' is not a valid version.
```

The  same behavior works in `OSX` where `wget` is not intslled.

**Comment by shyiko** [comment]
Fixed in https://github.com/shyiko/jabba/pull/296.
