### ISSUE TITLE
AdoptOpenJDK

### ISSUE THREAD

**Issue by gregorko** [shyiko/jabba#305]
Hello,

it would be nice if you could add the missing AdoptOpenJDK releases.
For example:
1.9.0-4
https://github.com/AdoptOpenJDK/openjdk9-binaries/releases/tag/jdk-9.0.4%2B11
1.10.2
https://github.com/AdoptOpenJDK/openjdk10-releases/releases/tag/jdk-10.0.2%2B13
https://github.com/AdoptOpenJDK/openjdk10-openj9-releases/releases/tag/jdk-10.0.2%2B13_openj9-0.9.0
1.11
https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/tag/jdk-11%2B28

**Comment by shyiko** [comment]
Done in https://github.com/shyiko/jabba/pull/307.
