### ISSUE TITLE
jabba deactivate fails on powershell

### ISSUE THREAD

**Issue by benediktarnold** [shyiko/jabba#309]
Hi!

I want to switch to my system installed java and tried `jabba deactivate`. It failed with the following message
(excuse my german system language, but it should make clear that `unset` is not a valid command)
```
unset : Die Benennung "unset" wurde nicht als Name eines Cmdlet, einer Funktion, einer Skriptdatei oder eines ausführbaren Programms erkannt. Überprüfen Sie die Schreibweise des Namens, oder ob der Pfad korrekt ist (sofern enthalten), und
wiederholen Sie den Vorgang.
In Zeile:3 Zeichen:1
+ unset JAVA_HOME_BEFORE_JABBA
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (unset:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Regards,
Ben

**Comment by benediktarnold** [comment]
Workaround for me was the usage of `link`
`jabba link system@1.8.0 C:\Progra~1\Java\jdk1.8.0_181`

Now I don't have the need anymore to deactivate jabba but can switch to my system installed java.

**Comment by shyiko** [comment]
Thank you, @benediktarnold!. It appears https://github.com/shyiko/jabba/blob/master/install.ps1#L55 is incomplete. I'll see what I can do.
