### ISSUE TITLE
Can't install JDK 1.10.0-2

### ISSUE THREAD

**Issue by doom369** [shyiko/jabba#317]
```
jabba install 1.10.0-2
Downloading 1.10.0-2 (http://download.oracle.com/otn-pub/java/jdk/10.0.2+13/19aef61b38124481863b1413dce1855f/jdk-10.0.2_linux-x64_bin.tar.gz) 
7073/7073
Extracting /tmp/jabba-d-176153959 to /pupkin/.jabba/jdk/1.10.0-2 
gzip: invalid header 

```

**Comment by shyiko** [comment]
It appears Oracle has [archived JDK 10](https://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase10-4425482.html) (https://www.oracle.com/technetwork/java/javase/downloads/jdk10-downloads-4416644.html). In other words, it now requires OTN account.
