### ISSUE TITLE
Allow switching to globally installed JDKs

### ISSUE THREAD

**Issue by ruurd** [shyiko/jabba#32]
I would like jabba to be able to switch to globally installed JDK versions. I happen to have a 1.7 and 1.8 installed globally (in /Library on macOS) and would really like them to be included in the list of jabba JVMs that can be switched to.

**Comment by shyiko** [comment]
Hi. Try `jabba link --help` (e.g. `jabba link system@1.8.20 /Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk`) (`jabba unlink system@1.8.20` to revert).

**Comment by ruurd** [comment]
I sort of hacked it by installing a JDK through jabba and reproduced it by symlinking to the system jdks... But thanks. Good show!
