### ISSUE TITLE
Install from file/directory

### ISSUE THREAD

**Issue by jkroepke** [shyiko/jabba#323]
Hi!

currently we are using multie version of java on our build machines. The Java Version are preinstalled by system. I want to use jabba as version switcher because setting a file like jabbarc is very developer friendly. In addition developer can test other version that are not available the system.

The Java versions on the system are not public. So `jabba install` will not fill the case here.

There is a chance to `install` a java version like `jabba install 11.0-company=file:///opt/jdk/11/`? Maybe a symlink can be create from the jabba home to the real directory instead copy it while developers can stil write `11.0-company` to the jabbarc, if why want to use it.

**Comment by shyiko** [comment]
Hi.

```sh
$ jabba link system@1.8.20 /Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk
$ jabba use system@1.8.20
```

Is this enough?

**Comment by jkroepke** [comment]
I see this part now in the README.md, but did not expect this feature. 

Thanks!
