### ISSUE TITLE
add Corretto please - https://aws.amazon.com/de/corretto/

### ISSUE THREAD

**Issue by svenruppert** [shyiko/jabba#339]

**Comment by shyiko** [comment]
Absolutely. We might want to wait for https://github.com/corretto/corretto-8/issues/2, though.

**Comment by tggreene** [comment]
It looks like the corretto team have added tgzs for linux and macos in preview 2: https://github.com/corretto/corretto-8/issues/2#issuecomment-454613240
https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/downloads-list.html

I've installed it locally with jabba with the following:

```
jabba install 1.8.192-corretto-p2=tgz+https://d3pxv6yz143wms.cloudfront.net/amazon-corretto-preview2-8u192-macosx-x64.tar.gz
```

**Comment by svenruppert** [comment]
thx for the info, will try it

**Comment by matthewmcgarvey** [comment]
Just wanted to bump this ticket since corretto 8 is out of preview.

To update the command above, I installed it using:
```
jabba install corretto@1.8.202-08=tgz+https://d2znqt9b1bc64u.cloudfront.net/amazon-corretto-8.202.08.2-macosx-x64.tar.gz
```

**Comment by shyiko** [comment]
Added in https://github.com/shyiko/jabba/pull/449 (auto-synced every 24h).
