### ISSUE TITLE
`jabba install 1.8` does not install `javac`

### ISSUE THREAD

**Issue by jamesbroadhead** [shyiko/jabba#350]
```
$ jabba use adopt@1.8.181-13
$ type javac
javac is /Users/jbo/.jabba/jdk/adopt@1.8.181-13/Contents/Home/bin/javac

$ jabba use 1.8.192

$ type java
java is /Users/jbo/.jabba/jdk/1.8.192/Contents/Home/bin/java
$ type javac
javac is /usr/bin/javac # note that this isn't inside the jabba dir
$ ls /Users/jbo/.jabba/jdk/1.8.192/Contents/Home/bin
ControlPanel  java    jcontrol  keytool  pack200     rmid         servertool  unpack200
_javaws       javaws  jjs       orbd     policytool  rmiregistry  tnameserv
```

This looks like only the JRE has been installed

**Comment by shyiko** [comment]
Sorry guys, for some reason "Notifications" were set to "Not Watching" and so I wasn't getting any messages for over 3 weeks. Fixed in [0.11.1](https://github.com/shyiko/jabba/blob/master/CHANGELOG.md#0111---2018-12-18).

**Comment by bogste** [comment]
Hi and thanks for fixing this in `master`! Looks like for version `11.2` this hasn't propagated to package managers like `Homebrew` -- instaling `jabba` using `brew` will have the broken JRE installing variant.

**Comment by shyiko** [comment]
#138 - homebrew is not currently supported.
