### ISSUE TITLE
JAVA_HOME points at hidden dir -- Intellij can't see it

### ISSUE THREAD

**Issue by lostvicking** [shyiko/jabba#352]
I'd like to point my Intellij at the Java I'm using in Jabba, however since the JAVA_HOME var points to a hidden dir, Intellij doesn't find it in the JDK selection file window 
JAVA_HOME=~/.jabba/jdk/zulu@1.8.181/Contents/Home

Any advice please?

**Comment by shyiko** [comment]
Use `cmd+shift+.` to show/hide hidden files.
