### ISSUE TITLE
archive extraction bug on Mac

### ISSUE THREAD

**Issue by tony--** [shyiko/jabba#356]
After installing jabba and adopt-openj9@1.11.0-1 on Mac, eclipse would not start.
A dialog was displayed with a message similar to "JVM Shared library does not contain the JNI_CreateJavaVM symbol".
In terminal, an error message indicated that ".jabba/jdk/adopt-openj9@1.11.0-1/Contents/MacOS/libjli.dylib: file too short".

[This SO answer](https://stackoverflow.com/a/44038265/273628) pointed me to the root cause.
For Java 11, Contents/MacOS/libjli.dylib should be a symbolic link pointing to ../Home/lib/jli/libjli.dylib (for Java 8 it should link to ../Home/jre/lib/jli/libjli.dylib), but instead it is a zero-length file.  This was the case for the 3 JDKs I installed on Mac using jabba:
adopt@1.11.0-1
adopt@1.8.192-12
adopt-openj9@1.11.0-1

I directly downloaded adopt-openj9@1.11.0-1 from the url listed in index.json and extracted it using archive utility.  Contents/MacOS/libjli.dylib was a valid symbolic link.  

Based on this, jabba's tar.gz extraction on Mac is not preserving symbol links.

**Comment by evacchi** [comment]
I think I can reproduce this on Linux when I install graal. The `bin/native-image` executable extracted by jabba is an empty file, but if I extract a tgz I downloaded manually it's a symlink

Any workaround, beside installing manually?

Thanks!

**Comment by shyiko** [comment]
My sincere apologies for the delayed response (for some reason "Notifications" were set to "Not Watching" and so I wasn't getting any messages for over 3 weeks).  

Fixed in 0.11.1.
