### ISSUE TITLE
ibm will not be shown with ls-remote

### ISSUE THREAD

**Issue by svenruppert** [shyiko/jabba#36]
jabba ls-remote
1.9.0-149
1.9.0-148
1.9.0-147
1.9.0-146
1.9.0-145
1.9.0-144
1.9.0-143
1.9.0-142
1.9.0-141
1.9.0-140
1.9.0-139
1.9.0-138
1.9.0-137
1.9.0-136
1.9.0-135
1.9.0-134
1.9.0-133
1.9.0-132
1.9.0-131
1.9.0-130
1.9.0-129
1.9.0-128
1.9.0-127
1.9.0-126
1.9.0-125
1.9.0-124
1.9.0-123
1.9.0-122
1.9.0-121
1.9.0-120
1.9.0-119
1.9.0-118
1.9.0-110
1.8.112
1.8.111
1.8.102
1.8.101
1.8.92
1.8.91
1.8.77
1.8.74
1.8.73
1.8.72
1.8.71
1.8.66
1.8.65
1.8.60
1.8.51
1.8.45
1.8.40
1.8.31
1.8.25
1.8.20
1.8.11
1.8.5
1.8.0
1.7.80
1.7.79
1.7.76
1.7.75
1.7.72
1.7.71
1.7.67
1.7.65
1.7.60
1.7.55
1.7.51
1.7.45
1.7.40
1.7.25
1.7.21
1.7.17
1.7.15
1.7.13
1.7.11
1.7.10
1.7.9
1.7.7
1.7.6
1.7.5
1.7.4
1.6.65
zulu@1.9.0-3
zulu@1.8.92
zulu@1.8.91
zulu@1.8.72
zulu@1.8.71
zulu@1.8.66
zulu@1.8.65
zulu@1.8.60
zulu@1.8.51
zulu@1.8.45
zulu@1.8.31
zulu@1.8.25
zulu@1.8.20
zulu@1.8.11
zulu@1.8.5
zulu@1.7.101
zulu@1.7.95
zulu@1.7.91
zulu@1.7.85
zulu@1.7.80
zulu@1.7.79
zulu@1.7.76
zulu@1.7.72
zulu@1.7.65
zulu@1.7.60
zulu@1.7.55

**Comment by svenruppert** [comment]
sorry..  tried it on OSX..

**Comment by shyiko** [comment]
@svenruppert No worries!
