### ISSUE TITLE
uninstall instructions for Jabba itself

### ISSUE THREAD

**Issue by leriksen** [shyiko/jabba#37]
perhaps an uninstall.ps1 ? or instructions in the readme.md

**Comment by shyiko** [comment]
Removing `~/.jabba` (on Linux/Mac OS X) / `%USERPROFILE%/.jabba` (on Windows) is pretty much all there is to it. During the installation initialization line is added to the profile but that thing will be rendered non-functional once `.jabba` directory is deleted. I'll update the readme.md.

**Comment by TraumaER** [comment]
I realize this is years old at this point, but to also remove the addition to the profile on Windows it was written to `%USERPROFILE%/Documents/powershell/Microsoft.PowerShell_profile.ps1` You can delete the line that is testing that the script exists. That will give a real clean slate.
