### ISSUE TITLE
Update Jabba image to something better

### ISSUE THREAD

**Issue by Roach** [shyiko/jabba#375]
The Jabba / Leia image on the README is pretty gross, both in quality and social connotations. 

May I suggest something more interesting, more fun:

Like

![image](https://user-images.githubusercontent.com/32463/50620758-35258980-0eb6-11e9-94c0-f619efd4561e.png)

or 

![image](https://user-images.githubusercontent.com/32463/50620804-846bba00-0eb6-11e9-94a1-2329dfb724f7.png)

**Comment by leonard84** [comment]
@Roach do you own the copyright for these images?

**Comment by shyiko** [comment]
Image removed. The last thing I want is to offend people. Sorry if anyone was put out by it.
