### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by bliaxiong** [shyiko/jabba#4]
I get this when I try to install and run...any ideas? OSX 10.10.5
``` shell
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   259  100   259    0     0    733      0 --:--:-- --:--:-- --:--:--   733
Installing v...

Skipped update of /Users/myUser/.bashrc (source string already present)
Skipped update of /Users/myUser/.bash_profile (source string already present)
Skipped update of /Users/myUser/.profile (source string already present)
Skipped update of /Users/myUser/.zshrc (source string already present)

Installation completed
(if you have any problems please report them at https://github.com/shyiko/jabba/issue)
/Users/myUser/.jabba/bin/jabba: line 1: {error:Not Found}: command not found

myUser~ $ jabba ls
/Users/myUser/.jabba/bin/jabba: line 1: {error:Not Found}: command not found
```

``` shell
myUser~ $ cat /Users/myUser/.jabba/bin/jabba
{"error":"Not Found"}
```

**Comment by shyiko** [comment]
Hi. My guess would be that [this request has failed](https://github.com/shyiko/jabba/blob/master/install.sh#L9). If it still does not work for you - please copy&paste output of `curl -o- https://api.github.com/repos/shyiko/jabba/releases/latest`. Thank you.

**Comment by bliaxiong** [comment]
``` shell
curl -o- https://api.github.com/repos/shyiko/jabba/releases/latest
{
  "message": "API rate limit exceeded for 161.225.129.111. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

**Comment by shyiko** [comment]
Alright, no more GitHub API calls :) It should work now.

**Comment by shyiko** [comment]
Fixed in https://github.com/shyiko/jabba/commit/8126b715c4fed8483145b15318baaf7d211a0609.

**Comment by bliaxiong** [comment]
It downloads the .dmg fine but runs into more errors:

```shell
jabba install 1.8
INFO[0001] Downloading 1.8.77 (http://download.oracle.com/otn-pub/java/jdk/8u77-b03/jdk-8u77-macosx-x64.dmg)
238309337/238309337
INFO[0328] Mounting /var/folders/wh/nm1wfd417498f990j4tr1mr1k2ph7j/T/jabba-d-563619953
INFO[0331] Extracting /var/folders/wh/nm1wfd417498f990j4tr1mr1k2ph7j/T/jabba-d-563619953 to /Users/myUser/.jabba/jdk/1.8.77
ERRO[0332] tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors

FATA[0332] 'if [ -f /var/folders/wh/nm1wfd417498f990j4tr1mr1k2ph7j/T/jabba-i-428306204/jabba-d-563619953-pkg/jdk*.pkg/Payload ]; then tar xvf /var/folders/wh/nm1wfd417498f990j4tr1mr1k2ph7j/T/jabba-i-428306204/jabba-d-563619953-pkg/jdk*.pkg/Payload -C /Users/myUser/.jabba/jdk/1.8.77; fi' failed: exit status 2
```

**Comment by shyiko** [comment]
Can you please copy&paste output of `/var/folders/wh/nm1wfd417498f990j4tr1mr1k2ph7j/T/jabba-i-428306204`? Thank you.

**Comment by bliaxiong** [comment]
``` shell
ls /var/folders/wh/nm1wfd417498f990j4tr1mr1k2ph7j/T/jabba-i-428306204
.			..			jabba-d-563619953	jabba-d-563619953-pkg
```

**Comment by shyiko** [comment]
Interesting, looks fine. What is your `tar --version`?

**Comment by bliaxiong** [comment]
tar (GNU tar) 1.28
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html
>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.

On Wed, Mar 30, 2016 at 2:39 PM, Stanley Shyiko <notifications@github.com>
wrote:

> Interesting, looks fine. What is your tar --version?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/shyiko/jabba/issues/4#issuecomment-203601204>
>



-- 
Thanks!

Blia Xiong
bliaxiong1@gmail.com

**Comment by shyiko** [comment]
Yep, this is it. GNU tar doesn't know how to handle this time of archive (works fine on BSD tar though). I'll make a fix. Thank you for helping narrowing it down :+1:

**Comment by shyiko** [comment]
Alright, could you please install 0.3.3 `curl -sL https://github.com/shyiko/jabba/raw/master/install.sh | JABBA_VERSION=0.3.3 bash && . ~/.jabba/jabba.sh` and confirm that it's fixed? Thank you.

**Comment by shyiko** [comment]
@bliaxiong

**Comment by bliaxiong** [comment]
Works. Does it not list existing Java installations?

**Comment by shyiko** [comment]
Thank you. 

> Works. Does it not list existing Java installations?
Right now - no. OS updates tend to mess up with system JDK (especially on Mac) so I've delayed that feature. If enough people ask for it - implementation is real simple. 

Anyway, thanks again for helping out.
