### ISSUE TITLE
file exist error.

### ISSUE THREAD

**Issue by ygpark2** [shyiko/jabba#43]
> ➜  ~ jabba help
jabba:2: file exists: /tmp/jabba-fd3.SWJP3I
➜  ~ .jabba/bin/jabba ls
1.9.0-152
1.8.112
zulu@1.9.0-3
zulu@1.8.112

Can you examine this problem? I can execute directly the command from the bin folder. The command with full path, however, doesn't seem to work.

Thank you.

**Comment by shyiko** [comment]
Hi.

It looks like you have noclobber enabled. You can read about it hear - http://www.victordodon.com/to-clobber-or-to-noclobber/. Adding `set +o noclobber` to your `$HOME/.bashrc` / `$HOME/.zshrc` should fix the problem.

**Comment by shyiko** [comment]
@ygpark2 I modified jabba.sh a little bit so that you wouldn't have to modify anything in your environment. Starting from now it doesn't matter whether noclobber is on or not. Just reinstall jabba and you should be good to go. Cheers!

**Comment by shyiko** [comment]
@ygpark2 and yes, thanks for the ticket!

**Comment by ygpark2** [comment]
@shyiko Thank you. it seems to work very nicely.
