### ISSUE TITLE
dunno about the image on the README

### ISSUE THREAD

**Issue by haywoood** [shyiko/jabba#431]
Yo! Hate to be ["that guy"](https://media.giphy.com/media/5UudNZgq6Zhv1dsWJ0/giphy.gif) but I've been successfully using this _great_ piece software, and was telling some co-workers about it, but felt kinda iffy about linking them because of the imagery on the README (I did, however). Not sure if we'd all be up to change it to something a little less, dunno.

Feel free to close this, just thought I'd drop in!

**Comment by shyiko** [comment]
Fair enough, Ryan. Image removed. (thanks for bringing it up!)
