### ISSUE TITLE
Download Oracle JDK 8 is not working ....

### ISSUE THREAD

**Issue by rogeriobueno** [shyiko/jabba#435]
Download by Oracle is not working ....

Downloading 1.8.212 (https://download.oracle.com/otn/java/jdk/8u212-b10/59066701cf1a433da9770636fbc4c9aa/jdk-8u212-linux-x64.tar.gz) 
4126/4126
Extracting /tmp/jabba-d-035594709 to /home/bueno/.jabba/jdk/1.8.212 
gzip: invalid header

**Comment by shyiko** [comment]
It appears Oracle JDK 8 is no longer available:
https://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

Also:
```
Important Oracle JDK License Update

The Oracle JDK License has changed for releases starting April 16, 2019.

The new Oracle Technology Network License Agreement for Oracle Java SE is substantially different from prior Oracle JDK licenses. The new license permits certain uses, such as personal use and development use, at no cost -- but other uses authorized under prior Oracle JDK licenses may no longer be available. Please review the terms carefully before downloading and using this product. An FAQ is available here. 

Commercial license and support is available with a low cost Java SE Subscription. 

Oracle also provides the latest OpenJDK release under the open source GPL License at jdk.java.net.
```

**Comment by leonard84** [comment]
Another reason for #115 and #430

**Comment by oletjens** [comment]
use the custom install feature:
`jabba install 1.8.0-custom=tgz+file:///tmp/server-jre-8u212-linux-x64.tar.gz`
