### ISSUE TITLE
gzip invalid header 

### ISSUE THREAD

**Issue by sainath199** [shyiko/jabba#436]
Downloading sjre@1.8.212 (https://download.oracle.com/otn/java/jdk/8u212-b10/59066701cf1a433da9770636fbc4c9aa/server-jre-8u212-linux-x64.tar.gz) 
0/1794
1/1794
Extracting /tmp/jabba-d-637610306 to /root/.jabba/jdk/sjre@1.8.212 
1794/1794
gzip: invalid header 
please help !!

**Comment by shyiko** [comment]
https://github.com/shyiko/jabba/issues/435

**Comment by oletjens** [comment]
use the custom install feature:
`jabba install 1.8.0-custom=tgz+file:///tmp/server-jre-8u212-linux-x64.tar.gz`
