### ISSUE TITLE
Perform a system-wide install of JDK and Jabba

### ISSUE THREAD

**Issue by boktai1000** [shyiko/jabba#437]
After reviewing the documentation and --help commands, I haven't been able to find out how to do this and don't believe it is possible. If it is possible, maybe this is something that needs to be further explained in the documentation or help procedures.

Essentially I would like to perform a global installation of the JDK and/or also install Jabba globally as well to a default system location, or specify a location for the installation (somewhere outside of a users home directory for example).

The use-case that I have is for using Jabba to install and manage versions of the JDK that will end up being used by Apache Tomcat which is running under a limited privileged user named `tomcat` that has no shell access and is fairly locked down as far as what the user can do, which is usually a part of security best practices for configuring web containers and running them under users.

This seems like something that I imagine Jabba could do, but again I couldn't figure out how after playing around with it for a while and trying to find examples of others using it. Maybe someone could help me understand how if this is possible, else consider this a feature request.

Thank you and have a great day!

**Comment by shyiko** [comment]
Sorry for the delay @boktai1000.

You can instal JDK to a custom location via `jabba install <jdk> --output /path/to/<jdk>/`, e.g.
```bash
$ jabba install zulu@1.8 -o /tmp/zulu-jdk
...
Extracting /tmp/jabba-d-976705173 to /tmp/zulu-jdk

$ /tmp/zulu-jdk/bin/java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (Zulu 8.38.0.13-CA-linux64) (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (Zulu 8.38.0.13-CA-linux64) (build 25.212-b04, mixed mode)
```
By default, JDKs installed with --output won't appear in `jabba ls` (they are considered to be "unmanaged"). To change that - use `jabba link system@<version> /path/to/<jdk>/`, e.g.
```bash
$ jabba link system@1.8.212-zulu /tmp/zulu-jdk

$ jabba ls
graalvm@19.0.0
system@1.8.212-zulu

$ jabba use system@1.8.212-zulu

$ java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (Zulu 8.38.0.13-CA-linux64) (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (Zulu 8.38.0.13-CA-linux64) (build 25.212-b04, mixed mode)
```
