### ISSUE TITLE
Please add Adopt Java 12 releases

### ISSUE THREAD

**Issue by gregorko** [shyiko/jabba#438]
AdoptOpenJDK has published there Java 12 releases. It would be nice if you could also add them.

https://adoptopenjdk.net/archive.html?variant=openjdk12&jvmVariant=hotspot
https://adoptopenjdk.net/archive.html?variant=openjdk12&jvmVariant=openj9

Thanks.

**Comment by shyiko** [comment]
done

```bash
$ jabba ls-remote adopt@
adopt@1.12.0-1
adopt@1.12.0-0
adopt@1.11.0-3
adopt@1.11.0-2
adopt@1.11.0-1
adopt@1.11.0-0
adopt@1.10.0-2
adopt@1.9.0-4
adopt@1.9.0-0
adopt@1.8.212-03
adopt@1.8.202-08
adopt@1.8.192-12
adopt@1.8.181-13
adopt@1.8.172-11
```
