### ISSUE TITLE
Include Reference Implementations for Java SE 8

### ISSUE THREAD

**Issue by boktai1000** [shyiko/jabba#446]
The download URLs for Windows and Linux can be found at https://jdk.java.net/java-se-ri/8 after accepting the Licensing Agreement. Is this something that is allowed to be added to Jabba?

If you go to https://jdk.java.net/ and select the hyperlink for 8 under Reference implementations, this is where the download links originate from.

When I referenced https://github.com/shyiko/jabba/blob/master/index.json to see what downloads were cataloged, I did not see these listed.

**Comment by shyiko** [comment]
Added in https://github.com/shyiko/jabba/pull/449 (auto-synced every 24h).
