### ISSUE TITLE
gzip: invalid header for JDK 1.11

### ISSUE THREAD

**Issue by mjclemente** [shyiko/jabba#454]
First of all, thanks for this tool and all the work that goes into maintaining it!

I imagine this is related to #317 #435 and #436 

When trying to download/use Oracle's JDK 11 or 11.0.3, I'm getting the same invalid header response:
```
→ jabba install 1.11.0-3
Downloading 1.11.0-3 (https://download.oracle.com/otn/java/jdk/11.0.3+12/37f5e150db5247ab9333b11c1dddcd30/jdk-11.0.3_osx-x64_bin.tar.gz)
4150/4150
Extracting /var/folders/ym/qt6c2jyx7zgcjzn5zpz2zj9r0000gn/T/jabba-d-612045349 to /Users/me/.jabba/jdk/1.11.0-3
gzip: invalid header
```

I know that I can use the custom install feature to get around this, but that seems to remove much of the convenience of using jabba, at least with Oracle. I'm assuming that this has to do with Oracle making changes to their download process. Just wanted to see if there was a fix possible, or if at this point is was just better to use OpenJDK or some other distro.

Thanks again!

**Comment by shyiko** [comment]
Hey Matthew,

It appears Oracle JDK 11 is no longer available (https://www.oracle.com/technetwork/java/javase/downloads/jdk11-downloads-5066655.html) (same as https://github.com/shyiko/jabba/issues/435#issuecomment-484957257). My recommendation is to switch to [Zulu, Amazon Corretto, Liberica JDK or GraalVM CE](https://github.com/shyiko/jabba#jabba--) (pick Zulu if unsure).

```bash
$ jabba ls-remote zulu@
zulu@1.12.0
zulu@1.12.0-1
zulu@1.11.0
zulu@1.11.0-3
zulu@1.11.0-2
zulu@1.11.0-1
zulu@1.10.0
zulu@1.10.0-2
zulu@1.10.0-1
zulu@1.9.0
zulu@1.9.0-7
zulu@1.9.0-4
zulu@1.9.0-1
zulu@1.9.0-0
zulu@1.8.212
zulu@1.8.202
zulu@1.8.201
zulu@1.8.192
zulu@1.8.181
zulu@1.8.172
zulu@1.8.163
zulu@1.8.162
zulu@1.8.152
zulu@1.8.144
zulu@1.8.131
zulu@1.8.121
zulu@1.8.112
zulu@1.8.102
zulu@1.8.92
zulu@1.8.91
zulu@1.8.72
zulu@1.8.71
zulu@1.7.222
zulu@1.7.211
zulu@1.7.201
zulu@1.7.191
zulu@1.7.181
zulu@1.7.171
zulu@1.7.161
zulu@1.7.154
zulu@1.7.141
zulu@1.7.131
zulu@1.7.121
zulu@1.7.111
zulu@1.7.101
zulu@1.7.95
zulu@1.6.119
zulu@1.6.113
zulu@1.6.107
zulu@1.6.103
zulu@1.6.99
zulu@1.6.97
zulu@1.6.93
zulu@1.6.89
zulu@1.6.87
zulu@1.6.83
zulu@1.6.79
zulu@1.6.77
```

(1.11.0-3 removed in https://github.com/shyiko/jabba/pull/456)

**Comment by mjclemente** [comment]
Thanks for getting back to me so quickly (and again, for the awesome project).

Just a question, by "No longer available", what exactly do you mean? Oracle JDK 11 can still be downloaded (from the page you linked to) and used (free for development). Just trying to understand the nature of the problem. Is it just the license change?

**Comment by shyiko** [comment]
@mjclemente try downloading jdk-11.0.3_linux-x64_bin.tar.gz for example. You'll be redirected to https://login.oracle.com/mysso/signon.jsp. In other words, downloading Oracle JDK 11 requires OTN account (compare that to https://www.oracle.com/technetwork/java/javase/downloads/jdk12-downloads-5295953.html). Does it make sense?

**Comment by mjclemente** [comment]
@shyiko Totally makes sense. I thought they required the account for all downloads at this point. Didn't realize the latest version could be downloaded without one. Thanks for your patience explaining!
