### ISSUE TITLE
Can add windows setting proxy to the document

### ISSUE THREAD

**Issue by leganck** [shyiko/jabba#488]
Can add windows setting proxy to the document

**Comment by drdamour** [comment]
agree, looks like Go respects the standard HTTP_PROXY and HTTPS_PROXY env vars, so in powershell i did:
```
$Env:HTTPS_PROXY = 'you awful corporate sponsored proxy here'
```

**Comment by wenmin92** [comment]
Without proxy, I can't use it.
![image](https://user-images.githubusercontent.com/6901815/71428068-5c91e980-26f9-11ea-950b-9d820bbdc403.png)
