### ISSUE TITLE
System JDK management

### ISSUE THREAD

**Issue by shyiko** [shyiko/jabba#5]
Add support for `jabba install system@1.8.0.20=/Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk`.

**Comment by stevenschlansker** [comment]
Or alternately, maybe just symlink the system location to the Jabba location?

**Comment by shyiko** [comment]
@stevenschlansker Yep, this is what I intended to do :)

**Comment by shyiko** [comment]
0.4.0
