### ISSUE TITLE
doesnt it work for browsers?

### ISSUE THREAD

**Issue by cassioac** [shyiko/jabba#52]
I´m trying to switch the java version for use with windows browsers, but it doesnt work, is this software meant only for terminal use?

**Comment by shyiko** [comment]
Hi @cassioac. 

All major browser vendors are dropping support for Java (to my knowledge Chrome & Edge already removed it, Firefox will in March this year (Firefox 52)). Together with [JEP 289: Deprecate the Applet API](http://openjdk.java.net/jeps/289) it makes little sense to invest time in it (even though it would be very easy - Java Control Panel (which you can access by executing `&"$(jabba which 1.8)\jre\bin\javacpl.exe"` in PowerShell terminal) is present and so all that is needed is a 32bit version of JDK).
