### ISSUE TITLE
Please add AdoptOpenJDK 13

### ISSUE THREAD

**Issue by gregorko** [shyiko/jabba#533]
AdoptOpenJDK 13 releases are available. It would be nice if you could add them.

Thanks..

**Comment by DanySK** [comment]
That would be useful for me as well

**Comment by normanmaurer** [comment]
Yes please... there are releases on the website now as well.

**Comment by shyiko** [comment]
Sorry for the delay, folks. "work" got in the way. 
Merged in https://github.com/shyiko/jabba/pull/537.
