### ISSUE TITLE
Windows: Unsupported OS msys with install.sh

### ISSUE THREAD

**Issue by olafurpg** [shyiko/jabba#535]
I'm using Jabba to install a configurable JVM in the new CI from GitHub, see https://github.com/olafurpg/setup-scala. It's working great on Ubuntu and macOS but I encountered the following error while trying to install Jabba on the new GitHub Actions CI using the `windows-latest` image

```
 Unsupported OS msys. If you believe this is an error -
  please create a ticket at https://github.com/shyiko/jabba/issues.
```

Full logs at https://github.com/olafurpg/sbt-ci-release/runs/235414051. Would it be possible to add support for the "msys" OS? The `windows-latest` image is Windows Server 2019, judging by https://help.github.com/en/articles/virtual-environments-for-github-actions#supported-virtual-environments-and-hardware-resources

PS. Thank you for Jabba! Jabba makes it a pleasure to manage multiple JVM installations on the same computer.

**Comment by kai2nenobu** [comment]
`install.sh` doesn't support msys but, `jabba` executable itself works in Windows (at least `install` command and `which` command).

I wrote a [workflow](https://github.com/kai2nenobu/github_actions_trial/blob/7d9fa59b68e487d54f47d61b8c8175c163a47a69/.github/workflows/jabba.yml) to download a OS-specific `jabba` and install jdk.  This workflow works in any OS ([workflow result](https://github.com/kai2nenobu/github_actions_trial/runs/240221588)).

 I think you can easily transform `Install java by jabba` step into JavaScript.

**Comment by olafurpg** [comment]
@kai2nenobu thank you for the pointers! I was able to get the installation working for Windows by porting your workflow to JavaScript 🙏 The GitHub Action can be found here https://github.com/olafurpg/setup-scala/ if anyone is interested.

Feel free to close this issue as a wontfix.
