### ISSUE TITLE
Update Jabba to support GraalVM 19.3.0 with Java 8 and Java 11

### ISSUE THREAD

**Issue by tovbinm** [shyiko/jabba#572]
GraalVM 19.3.0 that was released recently comes with Java 8 and 11 support - https://github.com/graalvm/graalvm-ce-builds/releases

**Comment by alexarchambault** [comment]
@shyiko Anything we can do to help with graalvm 19.3.0? Note that the address of the graalvm packages changed, it seems they live [here](https://github.com/graalvm/graalvm-ce-builds/releases) from now on. (That may explain why it's not taken into account by the "Synced …" PRs.)

**Comment by shyiko** [comment]
Sorry, folks. Never-ending fires at work. https://github.com/shyiko/jabba/pull/579 merged.

**Comment by alexarchambault** [comment]
Cool, thanks a lot for your work on jabba @shyiko!

**Comment by tovbinm** [comment]
Thank you!!

**Comment by arundilipan** [comment]
Question, if I wanted to use GraalVM 19.3.0/Java 8, how would I go about doing that? Would I just manually have to link it myself?

**Comment by arundilipan** [comment]
Hey @shyiko, I was wondering if there was a way that I could install GraalVM 19.3.0 with Java 8 instead of Java 11?

**Comment by arundilipan** [comment]
Never mind i think i got it!

**Comment by jvican** [comment]
@shyiko Could we add another tag to install the GraalVM 19.3.0 version for Java 8 instead of Java 11? The default graalvm@19.3.0 redirects to Java 11.
