### ISSUE TITLE
Instructions in README truncate user's PATH

### ISSUE THREAD

**Issue by masaeedu** [shyiko/jabba#59]
The `setx` instructions in your README will cause the user's PATH to be truncated if it is longer than 1024 characters. These instructions should be removed or replaced with an approach that does not truncate the PATH.

For anyone who runs into this, please see https://superuser.com/questions/812754/how-to-recover-from-path-being-truncated-to-1024-characters-by-setx for how to repair the PATH if you have restore points.

**Comment by shyiko** [comment]
@masaeedu Ouch... Fixed. Thank you.
