### ISSUE TITLE
Jabba doesn't list amazon-corretto@1.11.0-5.10.1 anymore

### ISSUE THREAD

**Issue by MaksymRybak** [shyiko/jabba#597]
Hello,
executing
`jabba install amazon-corretto@1.11.0-5.10.1`
we receive this error now:

> No compatible version found for amazon-corretto@1.11.0-5.10.1
> Valid install targets: [...all available versions at the moment...except amazon's one...]
> when executing 

Amazon versions were removed for some reason?

Thanks,
Maks

**Comment by plokhotnyuk** [comment]
Will support of `amazon-corretto` be restored or we should migrate to other JVMs?

**Comment by MaksymRybak** [comment]
> Will support of the `amazon-corretto` JVMs for MacOS be restored or we should migrate to others?
> 
> [Here](https://github.com/plokhotnyuk/jsoniter-scala/commit/61019bd455dccff3105ebbd02a33b6f07086ab76/checks?check_suite_id=410531848) is an example of failed CI build on Github Actions.

we also have our gitlab builds failing with the error _No compatible version found for amazon-corretto@1.11.0-5.10.1_. For the moment we are evaluating to make a fork and install jabba on our build agent, in the way to manage the JDK version updates manually.

**Comment by shyiko** [comment]
https://github.com/shyiko/jabba/pull/606. All restored.
