### ISSUE TITLE
Advance document (Install from window)

### ISSUE THREAD

**Issue by heowc** [shyiko/jabba#607]
I noticed a problem while installing this.

- Installation environment: Windows 10 Pro
- Exception: UnauthorizedAccess

So the solution I solved was after running:

```
Set-ExecutionPolicy RemoteSigned
```

We need to add this to the document.

**Comment by leobastiani** [comment]
Could you please reopen? It is still an issue

**Comment by leobastiani** [comment]
I had another question reading the documentation, should I run it with an Admin PS?
