### ISSUE TITLE
Add option to skip rc file update

### ISSUE THREAD

**Issue by AlexAegis** [shyiko/jabba#634]
Add a flag that skips line 123 to 155 in install.sh. It's really intrusive.

**Comment by shyiko** [comment]
Sounds good. If you send a PR - I'll merge it in.

**Comment by AlexAegis** [comment]
I created the pull request, after merging this can be closed

**Comment by AlexAegis** [comment]
(I discovered a typo so I'll open another)

**Comment by AlexAegis** [comment]
Thanks, for merging!
