### ISSUE TITLE
Java 1.13.0 can no longer get installed

### ISSUE THREAD

**Issue by DanySK** [shyiko/jabba#645]
Starting today, installation of `1.13.0` fails. See [these buids](https://travis-ci.org/github/DanySK/Gravis-CI/builds/676188612) (where `JDK=""`, the system falls back to trying installing the first JDK returned by `jabba ls-remote`, hence `1.13.0`).

This seems due to [the download link](https://download.oracle.com/otn-pub/java/jdk/13.0.2+8/d4173c853231432d94f001e99d882ca7/jdk-13.0.2_linux-x64_bin.tar.gz) being invalid Oracle-side

**Comment by willcohen** [comment]
The links have been updated to reflect 1.15, since 1.13 is no longer available. Does this resolve the issue?

**Comment by DanySK** [comment]
I think so.
However I think we could set up a pipeline on Travis testing every entry with a cronjob that runs daily. This way we could be notified quickly of failures and unavailable distributions.

**Comment by willcohen** [comment]
Until that happens, in the meantime, at the very least travis runs the autodiscovery job daily (it was getting stuck on failures before which was causing the listings to get stale) -- it should prune dead entries and replace them with working ones. As long as that keeps running and the changes get merged, it should have the same end effect!

**Comment by DanySK** [comment]
I did not check if something similar was in place already!
