### ISSUE TITLE
Support for Powershell 7

### ISSUE THREAD

**Issue by mrvonwyl** [shyiko/jabba#650]
I tried to install Jabba on Windows 10. I use Powershell 7.1.0-preview.1.
When I execute the installscript from the readme i get this error:

```
Invoke-Expression: Exception calling "GetString" with "1" argument(s): "Array cannot be null. (Parameter 'bytes')"
```

I believe this error happens on line 9 of the install.ps1 file which is downloaded.

Installation works if I manually set the version in the script:
```
$jabbaVersion = "0.11.2"
```

Unfotunately I have no clue about Powershell Scripts, so I would not know how to fix that.

**Comment by michaelcusick** [comment]
@mrvonwyl is this still an issue for you? There is an open PR for #752 to add jabba to chocolatey. This could be the recommended way to install it on Windows going forward.

**Comment by mrvonwyl** [comment]
@qBTp I checked again today and I didn't face any issues. However the download rates were very slow ond ubuntu as well as windows 10. But in the end everything worked as expected.
