### ISSUE TITLE
Examples for version install do not seem to work

### ISSUE THREAD

**Issue by pythys** [shyiko/jabba#660]
In the README file as well as "jabba help install" it is mentioned that you can do something like 
`jabba install 1.8`

However, I get the message `No compatible version found for 1.8` So either something is wrong with the code, or something is wrong with the documentation. Because the only way I can install java 8 is by specifying the full version (like adopt@1.8.0-242 for example)

**Comment by michaelcusick** [comment]
@pythys the README has been updated since with the latest version of the "default" jdk. The default jdk always points to the latest release. Right now it is 1.15.0.

**Comment by pythys** [comment]
Yup I can confirm correct behavior in later versions. It also works when issuing the command `jabba install adopt@1.8-0` which allows for avoiding the full JDK version. So I think it's good enough to close this ticket. Thank you for the follow up and update
