### ISSUE TITLE
Add option to specify Jabba storage directory

### ISSUE THREAD

**Issue by etki** [shyiko/jabba#67]
Hi!
I was getting acquainted with Jabba and found that currently there is no way to set Jabba directory - it will always stay `~/.jabba`. I think it would be cool to let user set it to anything else:
- It would allow perfectionists to keep their home clean
- It would allow system-global Jabba installs. System administrator may install Jabba as /usr/local/share/jabba with some default set of Java versions, and end users would have an option to keep a local Jabba installation if needed and switch from one to another.

**Comment by shyiko** [comment]
Hi @etki. Sure, this sounds reasonable. We could probably introduce JABBA_HOME env variable which when set would override default ~/.jabba location. Would this be enough for you?

**Comment by etki** [comment]
@shyiko Yes. To be honest, i'm perfectly fine with current setup, i'm just writing a chef cookbook and thinking about ways end users it could be used in future, so there are no real blockers for me now.

**Comment by davidwesst** [comment]
This may resolve the issue I'm facing on my machine. It's attached to a domain, so our group policy sets our HOME directory to a network share. When I run

`jabba install 1.8`

It ends up installing, complete with the administrator prompt, but after it is complete I get the following error:

```
H:\.jabba\jdk\1.8.131\bin\java.exe wasn't found. If you believe this is an error - please create a ticket at https://github.com/shyiko/jabba/issue (specify OS and command that was used)
```

I'm running Windows 10, with local admin privileges, but nothing seems to be copied over to the network share when it's "unpacked".

If I could specify a JABBA_HOME directory through an environment variable, that would likely solve the problem as I am assuming the script is having difficulty unpacking to the network share.

**Comment by shyiko** [comment]
Fair enough. I'll introduced JABBA_HOME over the weekend.

**Comment by shyiko** [comment]
Added in [0.7.0](https://github.com/shyiko/jabba/blob/master/changelog.md#070---2017-05-12). :tada:
