### ISSUE TITLE
MacOS jabba install zulu@1.8.252 - gzip: invalid header

### ISSUE THREAD

**Issue by enyrgy** [shyiko/jabba#685]
I'm seeing the following error when installing zulu.  I've tried running it with two different versions and got the same result.

```fish
Downloading zulu@1.8.252 (https://cdn.azul.com/zulu/bin/zulu8.46.0.19-ca-jdk8.0.252-macosx_x64.tar.gz)
Extracting /var/folders/6v/vy3kvgy5201flphy3r_7gs40vggrfb/T/jabba-d-684526190 to /Users/me/.jabba/jdk/zulu@1.8.252
gzip: invalid header
```

adopt installs without issues though.

**gzip version**: 1.10 
**jabba version**: 0.11.2
**Catalina version**: 10.15.5

**Comment by rafaelassumpcao** [comment]
well i got the same error here but i'm using linux  and was an attempting to install oracle version 1.13.0

**gzip version**: 1.10
**OS**: Ubuntu 20.04 LTS
**jabba version**: 0.11.2

output:
```
Downloading 1.13.0 (https://download.oracle.com/otn/java/jdk/13.0.2+8/d4173c853231432d94f001e99d882ca7/jdk-13.0.2_linux-x64_bin.tar.gz) 
4190/4190
Extracting /tmp/jabba-d-527161563 to /home/my_home/.jabba/jdk/1.13.0 
gzip: invalid header
```

there is some sort of more verbose output?

**Comment by enyrgy** [comment]
It doesn't look like it.

```fish
⋊> ~/g/st2docs on fix-broken-mistral-link  jabba install --help                                                                                                                                                           08:44:01
Download and install JDK

Usage:
  jabba install [version to install] [flags]

Examples:
  jabba install 1.8
  jabba install ~1.8.73 # same as ">=1.8.73 <1.9.0"
  jabba install 1.8.73=dmg+http://.../jdk-9-ea+110_osx-x64_bin.dmg

Flags:
  -o, --output jabba link   Custom destination (any JDK outside of $JABBA_HOME/jdk is considered to be unmanaged, i.e. not available to jabba ls, use, etc. (unless jabba linked))

Global Flags:
```

**Comment by shyiko** [comment]
@rafaelassumpcao It appears Oracle put 1.13.0 behind "require OTN account" wall now that Oracle JDK 14 is here. Added 14/Removed 13 in https://github.com/shyiko/jabba/pull/689.

@enyrgy Normally, you'll see `gzip: invalid header` only when download URL is broken. It does not appear to be the case here however. `jabba install zulu@1.8.252` works fine on my end. If it still does not work - try checking [https://cdn.azul.com/zulu/bin/zulu8.46.0.19-ca-jdk8.0.252-macosx_x64.tar.gz](https://cdn.azul.com/zulu/bin/zulu8.46.0.19-ca-jdk8.0.252-macosx_x64.tar.gz) content.

**Comment by enyrgy** [comment]
I didn't realize this but zulu is blocked from my corporate network.  I guess this was a recent blockage since it was working before.  Yay censorship?
