### ISSUE TITLE
Oracle JDK 1.14.0 and 1.14.0-1 no longer installable

### ISSUE THREAD

**Issue by bkabrda** [shyiko/jabba#706]
Hey 👋 it seems that Oracle JDKs 1.14.0 and 1.14.0-1 are no longer installable (at least on MacOS and Linux - I don't have access to a Windows machine, but I'm assuming it's the same here). I guess the problem could be that Oracle released 14.0.2 and potentially removed/changed links to the older versions. I'm currently pretty occupied, but probably can submit a PR next week (hopefully) unless someone fixes it until then.

**Comment by willcohen** [comment]
Replaced with a working 1.15.0 and autodiscovery regularly running again -- please reopen if this isn't addressing what you're looking for!
