### ISSUE TITLE
on Mac without install any jdk initially, I got "No Java runtime present, requesting install"

### ISSUE THREAD

**Issue by Azureym** [shyiko/jabba#711]
Initially, I didn't install any JDK
and then I install jabber with homebrew
and with jabber I install the `adopt@1.8.0-252`
jabber use adopt@1.8.0-252
this does not take effect and I got the system prompt asking me to install a jdk
![image](https://user-images.githubusercontent.com/4221416/89974463-c0bbea80-dc95-11ea-8b5f-38f59bc2c962.png)
![image](https://user-images.githubusercontent.com/4221416/89974491-cdd8d980-dc95-11ea-8b2d-ef02ac2501f1.png)

**Comment by michaelcusick** [comment]
@Azureym install jabba with the installation script instead of using Homebrew.
