### ISSUE TITLE
GraalVM 20.2.0 support

### ISSUE THREAD

**Issue by reibitto** [shyiko/jabba#714]
I don't mind creating a PR for this, but from what I can tell it seems like there's an automatic sync process that adds the URLs to `index.json`? If so, it might not make sense for me to create a PR. Does the sync tool just need to be triggered on your side?

**Comment by frank-dspeed** [comment]
good quest i was just wanting to do it manual

**Comment by willcohen** [comment]
I believe that shyiko/jabba-autodiscovery#8 fixes the failing autodiscovery process, which fails on the `.msi` files in the azul.com parsing, which should also get graal and everything else back up to date.

**Comment by frank-dspeed** [comment]
manual do it 
```
jabba install 20.2.0-graalvm=tgz+https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.2.0/graalvm-ce-java11-linux-amd64-20.2.0.tar.gz
jabba use 20.2.0-graalvm
```

**Comment by willcohen** [comment]
graalvm 20.2.0 is now available in `ls-remote`!

**Comment by agilesteel** [comment]
What about 20.3.0? It's been almost a week since the release. How often does the autodiscovery run?

**Comment by willcohen** [comment]
It's run daily but has been broken after zulu changed its numbering scheme (https://travis-ci.org/github/shyiko/jabba-autodiscovery). #744 added 20.3 as a temporary fix. I started to look at getting autodiscovery working this weekend but need to iron out a few more bugs first.
