### ISSUE TITLE
Add GraalVM AArch64 support for linux and Java 11

### ISSUE THREAD

**Issue by matsluni** [shyiko/jabba#716]
Looking here: https://github.com/graalvm/graalvm-ce-builds/releases, `aarch64` architecture is supported for java 11 on linux. Can this be added to the list of supported jdks?

What would be the process to add this? Just open a PR and add it manually?
Looking at some open PRs it looked like there is some script running to sync jdks.

**Comment by frank-dspeed** [comment]
@matsluni yes there is a extra autodiscovery that should be able to update that but no one did integrate that at present

**Comment by matsluni** [comment]
Thanks for the pointer @frank-dspeed. 
I will have a look there. Maybe I can contribute something.

**Comment by frank-dspeed** [comment]
@matsluni would be great if you could maybe issue a PR to it and add graalvm-ce@20.3.0 and 20.2 i simply have no time at present for that but it would be great if we get that going and then you could maybe issue a PR here and add github actions to automaticly use the result of the auto discovery

**Comment by frank-dspeed** [comment]
#714  is related

**Comment by willcohen** [comment]
Fixed with shyiko/jabba-autodiscovery#9.
