### ISSUE TITLE
Jabba installed, not working.

### ISSUE THREAD

**Issue by idk-pixel** [shyiko/jabba#717]
PS C:\Users\Kahaan Thakkar> jabba
C:\Users\Kahaan : The term 'C:\Users\Kahaan' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ C:\Users\Kahaan Thakkar\.jabba\bin\jabba.exe  --fd3 C:\Users\Kahaan T ...
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Kahaan:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\Kahaan Thakkar>

**Comment by Purple-Galaxy-Gaming** [comment]
Thats happening to me aswell!

**Comment by idk-pixel** [comment]
I know right!

**Comment by bromps** [comment]
@idk-pixel you need to escape the space in Windows:

```
C:\Users\Kahaan\ Thakkar.jabba\bin\jabba.exe
```

What does `which jabba` give you?

**Comment by idk-pixel** [comment]
> @idk-pixel you need to escape the space in Windows:
> 
> ```
> C:\Users\Kahaan\ Thakkar.jabba\bin\jabba.exe
> ```
> 
> What does `which jabba` give you?

What does `which jabba` give you mean?

**Comment by bromps** [comment]
Run the command `which jabba` and paste the output here.

**Comment by michaelcusick** [comment]
@shyiko please close this.

**Comment by idk-pixel** [comment]
oops.
