### ISSUE TITLE
Create github task that runs autodiscovery

### ISSUE THREAD

**Issue by frank-dspeed** [shyiko/jabba#720]
This should run autodiscovery and self update.

**Comment by willcohen** [comment]
Fixed with https://github.com/shyiko/jabba-autodiscovery/commit/6b36ad6d6d07478a6807c61f9875bfe2e31f8ef5, so travis is running regularly again. Do you see a reason that it needs to be a github task in particular?

**Comment by frank-dspeed** [comment]
nope jenkins is also fine as long as it ends up in a release.
