### ISSUE TITLE
Add adopt open jdk 15

### ISSUE THREAD

**Issue by marciofrayze** [shyiko/jabba#725]
I can't find the version 15 of adopt open jdk. Is it possible to add support to this version?

https://adoptopenjdk.net/?variant=openjdk15&jvmVariant=hotspot

ps. thanks for maintaining this project. It helps me a lot! :)

**Comment by LeoFuso** [comment]
I do too need this dependency, I use your project a lot. Thanks in advance!

**Comment by cd2357** [comment]
+1

**Comment by willcohen** [comment]
Fixed with a8b81e3!
