### ISSUE TITLE
Feature: Add `jabba default xxx` command

### ISSUE THREAD

**Issue by michaelcusick** [shyiko/jabba#729]
I would like to propose an alternative solution to the FAQ question *Q: How do I switch java globally?*.

Instead of needing elevated privileges to manipulate the global Java installation, the user's `PATH` could be modified in a way that the "default" Java version installed by jabba is set first on the path.  The only thing that the user would have to do is run the new command `jabba default java-version`, and then prepend the directory created by jabba to their `PATH`.

**What would `jabba default` do?**

The command would create a directory, `~/.jabba/bin` if it didn't already exist.  This directory should exist by default, since, in most cases, it contains the `jabba` executable.  Next, the command would create a symbolic link of the specified Java version's executable to this directory.  An example of the command for creating the symbolic link is `ln -sr ~/.jabba/jdk/adopt@1.8.0-252/bin/java ~/.jabba/bin/java `. 

The symbolic link needs to be removed when running the next `jabba default` and recreated.  I think that this should be done even if it links to the same location.  This way, the implementation logic is much simpler.

The only thing the user would need to do is prepend the `~/.jabba/bin` directory to the `PATH` if not done already.

**Comment by michaelcusick** [comment]
@shyiko what do you think about this feature?

**Comment by willcohen** [comment]
Are you talking about on Windows with powershell?

I don't totally understand how this would work globally for all users, if they don't themselves have jabba installed in their own home directories. My impression is that `jabba alias default ...` is still pretty easy to apply on a per-user basis on MacOS or Linux, which seems like it does largely the same thing.

**Comment by michaelcusick** [comment]
Oops, yes I missed that functionality when I wrote this a few months back. I was still a newbie jabba use then. 😄
