### ISSUE TITLE
Does this only work for Administrator session on Windows?

### ISSUE THREAD

**Issue by tinjaw** [shyiko/jabba#732]
I have an administrator account. If I run `cmd.exe` *As Administrator*, jabba seems to work just fine. However, if I just run a default `cmd.exe`, without specifying to run as admin, jabba doesn't seem to work at all.

Is this a limitation of jabba on Windows? Or might I need to config something differently?

`jabba --version` reports `0.11.2`.

**Comment by bromps** [comment]
It's probably a limitation of `cmd.exe`.  The **jabba** installation instructions for Windows user powershell.  Did you installed jabba in an administrator PowerShell?

As an addendum, I find the new Windows Terminal app to work quite well alongside WSL.

**Comment by tinjaw** [comment]
I read what you wrote above. I reinstalled jabba using PowerShell as Admin. It now works in PowerShell whether I am admin or not. CMD is still broken in terms of Jabba. I guess it is a case of "oh well. so what?" I guess I should finally make the change 100% to PowerShell anyways. Thanks.
