### ISSUE TITLE
Current Version Not Working On Current Versions of Widows 10 Or macOS 10.15

### ISSUE THREAD

**Issue by tinjaw** [shyiko/jabba#736]
In both cases `jabba use` and `jabba current` don't return anything and nothing I set. Although `jabba install` does work.

**Comment by willcohen** [comment]
Does `jabba ls` show results after you do an install? If so, then you should be able to do `jabba use` on the version you got installed.

**Comment by bromps** [comment]
Maybe we could put some responses when versions are not set but the commands are run?

For instance, if I install `java-1.8` and run `jabba use 1.8`, it would be cool if it returned "do you mean java-1.8?"  That could be helpful for new users.

**Comment by tinjaw** [comment]
This is what I get:

```
chaim@Chaims-Mac-mini ~ % jabba ls
openjdk@1.15.0
openjdk@1.15.0-1
openjdk@1.14.0
openjdk@1.14.0-2
chaim@Chaims-Mac-mini ~ % jabba use openjdk@1.15.0
chaim@Chaims-Mac-mini ~ % jabba current
chaim@Chaims-Mac-mini ~ % which java
/usr/bin/java
chaim@Chaims-Mac-mini ~ % java --version
No Java runtime present, requesting install.
chaim@Chaims-Mac-mini ~ % jabba ls
openjdk@1.15.0
openjdk@1.15.0-1
openjdk@1.14.0
openjdk@1.14.0-2
chaim@Chaims-Mac-mini ~ %
```

**Comment by bromps** [comment]
Did you happen to install jabba with brew on MacOS?  I ran into the same issue and had to uninstall with brew and then use the install script from the README.  No idea what to do about the Windows issue though.

**Comment by tinjaw** [comment]
I did use brew on Mac. Let me try your workaround and report back.

**Comment by tinjaw** [comment]
The workaround has solved the issue on my Mac. I will further investigate my Windows box. Maybe somebody out in the wild will have a suggestion as to what might be causing the issue.
