### ISSUE TITLE
how to fix

### ISSUE THREAD

**Issue by alonalibarmn** [shyiko/jabba#745]
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 0
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic reboot: last crash occurred less than 60 seconds ago.

**Comment by michaelcusick** [comment]
How is this related to jabba?

**Comment by willcohen** [comment]
This appears to be related to whatever you're running, not jabba. Reopen if you think something isn't installing correctly!
