### ISSUE TITLE
Bedrock Vinella not working HELP!!!

### ISSUE THREAD

**Issue by Doomguy3232** [shyiko/jabba#746]
every time i try to make a bedrock server 1. i dont get the EULA and 2. it says that the .jar file isnt showing up soooo... help!

**Comment by Doomguy3232** [comment]
it dosent show the versions too

**Comment by Doomguy3232** [comment]
but im not in the discord so

**Comment by michaelcusick** [comment]
@shyiko close this please.

**Comment by willcohen** [comment]
@Doomguy3232 this appears to be related to what you're running, not jabba itself. All jabba does is help you get java installed, not be sure that the software you're running is working correctly.

**Comment by Doomguy3232** [comment]
Ah ok thanks!
