### ISSUE TITLE
error making bombsquad server

### ISSUE THREAD

**Issue by m4x-m3rcury** [shyiko/jabba#749]
**hi im trying in this days to host a bombsquad server on falixnodes at 12:00 am when i go in the dashboard page and i click on start it gives me this error:
**`Could not find server.jar`**
if u can help me i be very happy and grateful.**

**Comment by michaelcusick** [comment]
Close this please.

**Comment by willcohen** [comment]
this appears to be related to what you're running, not jabba itself. All jabba does is help you get java installed, not be sure that the software you're running is working correctly.
