### ISSUE TITLE
Eclipse integration

### ISSUE THREAD

**Issue by inancgumus** [shyiko/jabba#76]
Do you know a way to integrate Jabba with Eclipse?

**Comment by shyiko** [comment]
Hi.

To my knowledge there are no plugins that allow to use jabba for JDK installation / discovery from within the Eclipse (I assume this is what you are after). There is nothing stopping you from adding JDK installed by the `jabba`, though (Window -> Preferences -> Installed JREs -> Add... -> specify path to JDK (e.g. "/home/username/.jabba/jdk/1.8.77") (`jabba which $(jabba current)`).

**Comment by inancgumus** [comment]
@shyiko Yeah, I did that like that, I was after for some tight integration like you said. I wish I could find a time to make such a plugin. Thanks!

**Comment by shyiko** [comment]
@inancgumus If you ever do find the time, let me know. I'd gladly add a link to the readme.md :wink:
