### ISSUE TITLE
Windows 10 Powershell 5.1 install error - Unexpected token 'if' in expression or statement

### ISSUE THREAD

**Issue by aSemy** [shyiko/jabba#773]
### Issue

On Windows 10, when I run the install command, I get an error: `Unexpected token 'if' in expression or statement.` Full log below.

This could be related to encoding? I know there's lots of previous issues about installing Jabba on Powershell, because Powershell has issues with file encodings and not defaulting to UTF8.

I think this is caused by this PR #534 

I am running Powershell 5.1: `Get-Host | Select-Object Version` = 5.1.18362.1171

### Workaround 

The version before the merge installs (no further testing done)
 
 * https://github.com/shyiko/jabba/blob/cb82662a564af4752a84aa7dbc420f928eef6663/install.ps1

As a work around, I modified the script to install the previous version.

```PowerShell
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
Invoke-Expression (
  Invoke-WebRequest https://raw.githubusercontent.com/shyiko/jabba/cb82662a564af4752a84aa7dbc420f928eef6663/install.ps1 -UseBasicParsing
).Content
```

### Log

```PowerShell
PS C:\WINDOWS\system32> [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12                 >> Invoke-Expression (
>>   Invoke-WebRequest https://github.com/shyiko/jabba/raw/master/install.ps1 -UseBasicParsing
>> ).Content
Invoke-Expression : At line:67 char:15
+ $sourceJabba="if (Test-Path `"$jabbaHome\jabba.ps1`") { . `"$jabbaHom ...
+               ~~
Unexpected token 'if' in expression or statement.
At line:74 char:6
+ if ("$(Get-Content $profile | Select-String "\\jabba.ps1")" -eq "")
+      ~~
Unexpected token '$(' in expression or statement.
At line:74 char:59
+ if ("$(Get-Content $profile | Select-String "\\jabba.ps1")" -eq "")
+                                                           ~~~~~~~~~
Unexpected token '" -eq "")
{
    Write-Host "' in expression or statement.
At line:76 char:17
+     Write-Host "Adding source string to $profile"
+                 ~~~~~~
Unexpected token 'Adding' in expression or statement.                                                                   At line:90 char:1                                                                                                       + "@                                                                                                                    + ~~                                                                                                                    The string is missing the terminator: ".
At line:2 char:1
+ Invoke-Expression (
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ParserError: (:) [Invoke-Expression], ParseException
    + FullyQualifiedErrorId : UnexpectedToken,Microsoft.PowerShell.Commands.InvokeExpressionCommand
```

**Comment by tyrng** [comment]
I too, had to use the previous install script to workaround this issue.

**Comment by aSemy** [comment]
I'm also concerned that `SetEnvironmentVariable` in #534 might cause issues

https://hahndorf.eu/blog/AddingToPathVariable.html

After using `SetEnvironmentVariable` the author notes

> There are three problems here:
>
> * The location C:\Users\name\AppData\Local\Microsoft\WindowsApps has been copied from a user specific %path% entry to a machine specific one.
> 
> * %SystemRoot% and %ToolsFolder% are now stored as their expanded hard-coded values, not variables.
> 
> * The type of the registry value changed from REG_EXPAND_SZ to REG_SZ

**Comment by willcohen** [comment]
Reverted #534 with 57b8cd36b. Apologies -- this is what happens when a macOS user doesn't read the changes closely enough. Added #775 as placeholder for now.
