### ISSUE TITLE
Please setup JAVA_HOME for current JDK

### ISSUE THREAD

**Issue by liaoya** [shyiko/jabba#79]
Many Java application rely on JAVA_HOME like ant,, maven and tomcat. They will refuse to run if this environment variable does not exists.

**Comment by shyiko** [comment]
Hi. This is what `jabba use` (e.g. `jabba use 1.8`) is for (both PATH & JAVA_HOME are set). If you want to change global (system-wide) JAVA_HOME see https://github.com/shyiko/jabba#faq.
