### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by antyriad** [shyiko/jabba#8]
When I try to use jabba, this error message is always displayed:

```
jabba:2: permission denied: /home/ngo/.jabba/bin/jabba
rm: remove regular empty file ‘/tmp/jabba-fd3.qAk9Ma’?
```
> `qAk9Ma` string is always different.

I think installation fails, how can I fix it ?

**Comment by shyiko** [comment]
Hi. Try [reinstalling jabba](https://github.com/shyiko/jabba/raw/master/#installation). If that doesn't help - please copy & paste the output of `uname -a`, `ls -l ~/.jabba/bin/jabba`. What Linux are you running (also which shell)? Thanks.

**Comment by antyriad** [comment]
It fails again. Nota : I'm using a corporate proxy

Full Command output :

    curl -sL https://github.com/shyiko/jabba/raw/master/install.sh | bash && . ~/.jabba/jabba.sh
    Installing v ... Proxy Access Denied message ...
    curl: option -: is unknown
    curl: try 'curl --help' or 'curl --manual' for more information
    Skipped update of /home/ngo/.bashrc (source string already present)
    Skipped update of /home/ngo/.bash_profile (source string already present)
    Skipped update of /home/ngo/.profile (source string already present)
    Skipped update of /home/ngo/.zshrc (source string already present)
    
    Installation completed
    (if you have any problems please report them at https://github.com/shyiko/jabba/issue)
    jabba:2: exec format error: ~/.jabba/bin/jabba
    rm: remove regular empty file ‘/tmp/jabba-fd3.qwrOmh’?

If I display the tree of ~/.jabba

    tree -s
    .
    ├── [       4096]  bin
    │   └── [          0]  jabba
    ├── [        468]  jabba.fish
    └── [        390]  jabba.sh

> `~/antyriad/.jabba/bin/jabba` size is 0

It seams failed to download jabba binary file (Why install.sh said 'Installation completed ?').

Then, I downloaded it manually into `.jabba/bin/jabba` :

    wget https://github.com/shyiko/jabba/releases/download/0.3.3/jabba-0.3.3-linux-amd64

Now it works, but for each call, I have a line :

    rm: remove regular empty file ‘/tmp/jabba-fd3.eH4PRD’?

My pull request fix this issue.

**Comment by shyiko** [comment]
See 266a9fdd5bfeb42559b0c03a6fcd255ae397b6ef, 10fbe635c55dbd336bd4a5556b158918f4411026 and 27fe6dbe2ee1dd7bf285853f128985c5058d360f.
