### ISSUE TITLE
Cannot install Java 7 on MacOSx

### ISSUE THREAD

**Issue by aruizca** [shyiko/jabba#81]
MacOSx 10.12.5

```
MacBook-Pro:~ aruizca$ jabba install 1.7
Downloading 1.7.80 (http://download.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-macosx-x64.dmg)
7073/7073
Mounting /var/folders/6z/tqx78p3d7x7ftzx_5h2jk8zm0000gn/T/jabba-d-056495298
hdiutil: mount failed - image not recognized

'hdiutil mount -mountpoint /var/folders/6z/tqx78p3d7x7ftzx_5h2jk8zm0000gn/T/jabba-i-540861753/jabba-d-056495298 /var/folders/6z/tqx78p3d7x7ftzx_5h2jk8zm0000gn/T/jabba-d-056495298' failed: exit status 1
```

**Comment by aruizca** [comment]
I think all Oracle JDKS with version < 8 are now behind a curtain, protected by user account login.

See what happen to SDKMAN: https://medium.com/@sdkman_/about-proprietary-jdks-on-sdkman-6052525a152e

**Comment by amukas** [comment]
Hi, I've got the same issue, Oracle archived 1.7.
As a workaround, you can download dmg (http://download.oracle.com/otn/java/jdk/7u80-b15/jdk-7u80-macosx-x64.dmg) and install from a local image.
`jabba install 1.7.80=dmg+file:///Users/oleksiim/Downloads/jdk-7u80-macosx-x64.dmg`

**Comment by amukas** [comment]
I would use zulu, since it's free and up to date.

**Comment by aruizca** [comment]
I would if I could 😉

On 5 Jun. 2017 11:49, "amukas" <notifications@github.com> wrote:

I would use zulu, since it's free and up to date.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/shyiko/jabba/issues/81#issuecomment-306148460>, or mute
the thread

**Comment by aruizca** [comment]
I have uploaded the dmg file to my dropbox so I can use it in a CI engine and it fails when I execute:
```
jabba install 1.7.80=dmg+https://www.dropbox.com/s/37whatever/jdk-7u80-macosx-x64.dmg?dl=0
```
I get error:
```
hdiutil: mount failed - image not recognized

'hdiutil mount -mountpoint etc etc' failed: exit status 1
```

**Comment by shyiko** [comment]
Hi everyone. Yeah, at the moment JDK 7 is not available (I'm pondering the idea of asking for oracle account when installing Oracle JDK below 8 but I haven't decided yet - still looking for a better way to handle this). Having said that, installing from URL should work just fine. 

@aruizca https://www.dropbox.com/s/37whatever/jdk-7u80-macosx-x64.dmg?dl=0 returns 404. Make sure you can download file with curl and you'll be good to go. Please let me know if you have any problems. Thank you.

**Comment by shyiko** [comment]
Alright. 
I think there is no point in keeping this ticket open any longer. Considering that:
- JDK 1.6 & 1.7 are available from Zulu (`jabba ls-remote "zulu@<1.8"`) &  
IBM (`jabba ls-remote "ibm@<1.8"`) 
- both 1.6 & 1.7 reached the "End of Public Updates"
- there is no way to predict what Oracle will come up with next

I don't think it's worth the effort.

**Comment by aruizca** [comment]
You are correct @shyiko As long as you are able to install a JDK from a custom url, Jabba seems the best option ATM.
Thanks!

**Comment by shyiko** [comment]
@aruizca :handshake:

**Comment by jcrben** [comment]
Also got this for 1.9.0-1:
![image](https://user-images.githubusercontent.com/5614134/35259096-993cdec2-ffb8-11e7-852d-ee45dbc1f449.png)

**Comment by shyiko** [comment]
@jcrben fixed in https://github.com/shyiko/jabba/pull/137 (note that 1.9.0-1 was updated to 1.9.0-4)
