### ISSUE TITLE
Link to path with spaces (Windows)

### ISSUE THREAD

**Issue by rubin55** [shyiko/jabba#84]
PS C:\Users\rubin> jabba link system@1.6.151 'C:\Program Files\Java\oracle-jdk6\'
C:\Program\bin\java.exe wasn't found. 

If you believe this is an error - please create a ticket at https://github.com/shyiko/jabba/issue (specify OS and command that was used)

**Comment by shyiko** [comment]
Hi @rubin55. Thank you for the ticket. Enclosing path in """ (triple quotes, e.g. `"""C:\Program Files\Java\oracle-jdk6"""`) should work fine (same as "'). If you have a solution for [single quote](https://github.com/shyiko/jabba/blob/master/install.ps1#L51) that would be wonderful.

**Comment by shyiko** [comment]
https://stackoverflow.com/a/33466762/482225 looks like a possible solution for 'single quote'.
