### ISSUE TITLE
'...' is not a valid version

### ISSUE THREAD

**Issue by tangjm** [shyiko/jabba#851]
I am currently running Ubuntu 20.04.4 LTS (GNU/Linux 5.10.16.3-microsoft-standard-WSL2 x86_64).

I tried installing jabba for managing my Java versions but ran into this issue: 

When I run these commands in bash

```bash
export JABBA_VERSION=...
curl -sL https://github.com/shyiko/jabba/raw/master/install.sh | bash && . ~/.jabba/jabba.sh
```

I get the following error message:

```bash
'...' is not a valid version.
```

**Comment by GraxMonzo** [comment]
Hi, @tangjm
Replace `...` with valid jabba version like this: `export JABBA_VERSION=0.11.2`

**Comment by tangjm** [comment]
> Hi, @tangjm Replace `...` with valid jabba version like this: `export JABBA_VERSION=0.11.2`

Thanks! I thought '...' stood for some bashism, this makes more sense now.

**Comment by JimLynchCodes** [comment]
@GraxMonzo I also think it is terrible user experience to have a half-complete command in the readme. 😔
