### ISSUE TITLE
Jabba Install Doesn't Work

### ISSUE THREAD

**Issue by JimLynchCodes** [shyiko/jabba#855]
I am on macOs version 12.4 intel chip.

I set the Jabba version and run the curl command, but I just get the error afterwards that "/Users/jim/.jabba/bin/jabba does not appear to be a valid binary."

![Screen Shot 2023-09-28 at 1 12 06 PM](https://github.com/shyiko/jabba/assets/5354163/f2e3a7dd-e080-4f6d-87a8-0d5f927f7560)

**Comment by JimLynchCodes** [comment]
The `export JABBA_HOME=...` in README is very confusing. Can't we make setting this env var optional?

**Comment by bajalnyt** [comment]
The version you need to export is 0.11.2. And it is optional, because if you don't pass it; it defaults to latest. [See](https://github.com/shyiko/jabba/blob/master/install.sh#L49-L52)

**Comment by stephankoelle** [comment]
https://github.com/Jabba-Team/jabba

**Comment by JimLynchCodes** [comment]
thanks all 👍
