### ISSUE TITLE
Jabba for Raspberry Pi

### ISSUE THREAD

**Issue by charllie** [shyiko/jabba#87]
Can you build a release for Raspberry Pi (arm) please? The script installs an Intel 32 instead.
Thank you.

**Comment by shyiko** [comment]
@charllie done :tada:. 

NOTE: I don't have armv8 (64bit) device so I only tested it on my RPI 2 / Model B which is armv7hf (32bit). Let me know if you have any issues.

**Comment by shyiko** [comment]
(links to JDKs were added in https://github.com/shyiko/jabba/commit/529d0ddc28df8450668d7cefc108822236aafbc0)

**Comment by charllie** [comment]
Thank you. It is working fine! 🎉
