### ISSUE TITLE
Feature Request : Add option for Azul Zing

### ISSUE THREAD

**Issue by abhi18av** [shyiko/jabba#97]
Hi @shyiko 

I discovered `jabba` a few days ago and this is a fantastic tool - thanks :+1: 

However, I was wondering if you'd add support for  `Azul Zing JDK`. I know that It requires license keys and stuff so perhaps it'd be sensible to just operate upon the downloaded version like,

`jobba zing@xyz ~/path/to/zing/tar`

Looking forward to your thoughts on this one.

**Comment by shyiko** [comment]
Hi @abhi18av. 

Unless Azul grants us permission to download their JDK there isn't much we can do BUT
 you should be able to install Zing JDK (provided you have a tarball / zip) with 
```
jabba install zing@1.8.0=tgz+http://....tar.gz
jabba install zing@1.8.0=zip+file:///path/to/....zip
```

**Comment by abhi18av** [comment]
Whoops, forgot to reply earlier. 

@shyiko, yup this is just as great :+1:
