### ISSUE TITLE
Error with leiningen's detection of Java

### ISSUE THREAD

**Issue by abhi18av** [shyiko/jabba#99]
Hi @shyiko 

I think that the way `jabba` currently works raises an error with `leiningen`. 

It works fine while I'm in the terminal but when I use the `spacemacs` and `cider` for clojure developement it's not able to detect the installed java at all.

I've raised an issue here.

https://github.com/syl20bnr/spacemacs/issues/9501

**Comment by abhi18av** [comment]
I do realize that there's a `default` command in `jabba` but doesn't seem to work either.

```sh
 jabba alias default zulu@1.8.144

```

**Comment by shyiko** [comment]
Hi @abhi18av. 

`jabba use` modifies JAVA_HOME & PATH env vars inside "current session" only. Either make sure Emacs is launched in the environment where JAVA_HOME & PATH have been modified (when you open a new shell `jabba use default` is called automatically) or [FAQ > How do I switch java globally?](https://github.com/shyiko/jabba#faq).

**Comment by abhi18av** [comment]
Ah, I see. Thanks)

Could you tell me how to configure that for macOS, it's not there on the
Readme.

**Comment by shyiko** [comment]
@abhi18av usually sourcing `~/.bashrc` from `~/.bash_profile` is enough (see https://ss64.com/osx/syntax-bashrc.html for details).

**Comment by abhi18av** [comment]
Yup, that did it! Thanks man :+1:
